spring.application.name=tutr-backend
spring.datasource.url=jdbc:mysql://localhost:3306/tutr_db
spring.datasource.username=root
spring.datasource.password=Root@1947

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# File upload configuration


# Base upload directory
file.upload-dir=uploads

# Multipart configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=${java.io.tmpdir}

# Tomcat configuration
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-form-post-size=50MB